### PR TITLE
Readme: fix a typo

### PR DESCRIPTION
**Pull request by ForNeVeR**

### CODE REVIEW

**Comment by keddelzz** [comment]
Thank you for fixing this!

**Review by keddelzz — APPROVED** [review]

**Comment by rexim** [comment]
@ForNeVeR 3 reviewers for fixing a typo? Really? :)

**Review by rexim — APPROVED** [review]
LGTM :+1:

**Comment by keddelzz** [comment]
Thanks guys, for the reviev :+1:

**Pull request merged**
